apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/thainguyen101b/ecommerce/k8s?ref=k8s-setup

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: ecommerce-config

images:
  - name: ecommerce
    newName: ghcr.io/thainguyen101b/ecommerce
    newTag: latest

replicas:
  - name: ecommerce
    count: 2