apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
spec:
  template:
    spec:
      containers:
        - name: ecommerce
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: ecommerce-postgres-ecommerce-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret